version: 2.0

references:
  container_config: &container_config
    docker:
      - image: google/cloud-sdk
    environment:
      PROJECT_NAME: orangesys
      CLOUDSDK_COMPUTE_ZONE: asia-northeast1-c
      ORG_PATH: "github.com/orangesys"
      REPO_PATH: "${ORG_PATH}/${CIRCLE_PROJECT_REPONAME}"
      BASH_ENV: .circleci/checktag.sh
  install_docker_client: &install_docker_client
    run:
      name: Install docker client
      command: |
        set -x
        VER="17.05.0-ce"
        curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
        tar -xz -C /tmp/ -f /tmp/docker-$VER.tgz
        mv /tmp/docker/* /usr/bin
  restore_cache: &restore_cache
    keys: 
      - v1-{{ .Branch }}

jobs:
  build_container:
    <<: *container_config
    steps:
      - checkout
      - setup_remote_docker
      - *install_docker_client
      - run:
          name: Build container images
          command: |
            docker build --tag "orangesys/${CIRCLE_PROJECT_REPONAME}:${version}" .
            docker images

      - run:
          name: save container image to workspace
          command: |
            [ ! -d /caches ] && mkdir /caches
            docker save -o /caches/${CIRCLE_PROJECT_REPONAME}.tar "orangesys/${CIRCLE_PROJECT_REPONAME}:${version}"
      - save_cache:
          key: v1-{{ .Branch }}
          paths:
            - "/caches"            

  push_container:
    <<: *container_config
    steps:
      - checkout
      - restore_cache: *restore_cache  
      - setup_remote_docker
      - *install_docker_client
      - run:
          name: Load Docker image layer cache
          command: |
            docker load -i /caches/${CIRCLE_PROJECT_REPONAME}.tar
            docker images
      - run:
          name: Show docker images & set tag & push docker hub and gcloud
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push orangesys/${CIRCLE_PROJECT_REPONAME}:${version}
            curl -X POST https://hooks.microbadger.com/images/orangesys/${CIRCLE_PROJECT_REPONAME}/0dZgaMEbOqgcB9nRmLoM_C3JEkY=

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_container:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/ 
      - push_container:
          requires:
            - build_container
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*(-.*)*/
            branches:
              ignore: /.*/